### ISSUE TITLE
다중 체크 박스 추가

### ISSUE THREAD

**Issue by ZayneLee** [ZayneLee/spring-section3#8]
## Description
단일 체크 박스 추가

## To-Do
- 판매 여부
- [ ] 판매 오픈 여부
- [ ] 체크 박스로 선택할 수 있다.
- 등록 지역
- [ ] 서울, 부산, 제주
- [ ] 체크 박스로 다중 선택할 수 있다.
- 상품 종류
- [ ] 도서, 식품, 기타
- [ ] 라디오 버튼으로 하나만 선택할 수 있다.
- 배송 방식
- [ ] 빠른 배송
- [ ] 일반 배송
- [ ] 느린 배송
- [ ] 셀렉트 박스로 하나만 선택할 수 있다.

## ETC
